# Usar la imagen base deseada
FROM python:3.9

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY . .

# Instalar las dependencias de la aplicación
RUN pip install --no-cache-dir -r requirements.txt

# Definir las variables de entorno con el SHA del commit, el autor del commit y la fecha de compilación
ARG GIT_COMMIT
ARG GIT_AUTHOR
ARG BUILD_DATE

ENV COMMIT_SHA=${GIT_COMMIT}
ENV COMMIT_AUTHOR=${GIT_AUTHOR}
ENV BUILD_DATE=${BUILD_DATE}

# Exponer el puerto en el que la aplicación se ejecuta
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]